# Generated by Django 5.1.1 on 2024-09-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_food_status_restaurant_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='status',
        ),
    ]
