# Generated by Django 5.1.1 on 2024-10-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_food_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
