# Generated by Django 5.1.1 on 2024-10-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
