# Generated by Django 5.1.1 on 2024-10-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_order_total_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
