# Generated by Django 5.1.1 on 2024-10-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='pickup_time',
            new_name='elan_muddeti',
        ),
        migrations.AddField(
            model_name='food',
            name='mehsul_muddeti',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
