# Generated by Django 5.1.1 on 2024-10-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.FloatField(default="4.5"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.FloatField(default="4.4"),
            preserve_default=False,
        ),
    ]
