# Generated by Django 5.1.1 on 2024-10-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_pickup_time_food_elan_muddeti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='elan_muddeti',
        ),
    ]
