# Generated by Django 5.1.1 on 2024-10-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_food_elan_muddeti'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='elan_muddeti',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
