# Generated by Django 5.1.1 on 2024-10-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_restaurant_latitude_restaurant_longitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="pickup_time",
            new_name="elan_muddeti",
        ),
        migrations.RenameField(
            model_name="orderfood",
            old_name="food_id",
            new_name="food",
        ),
        migrations.RemoveField(
            model_name="food",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="order",
            name="food_items",
        ),
        migrations.RemoveField(
            model_name="orderfood",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="longitude",
        ),
        migrations.AddField(
            model_name="food",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="food_images/"),
        ),
        migrations.AddField(
            model_name="food",
            name="mehsul_muddeti",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="food",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderfood",
            name="order",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="api.order",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderfood",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="logo",
            field=models.ImageField(default=None, upload_to="restaurant_logos/"),
        ),
    ]
