# Generated by Django 5.1.1 on 2024-10-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_food_elan_muddeti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
    ]
