# Generated by Django 5.1.1 on 2024-10-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_restaurant_food_restaurant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
