# Generated by Django 5.1.1 on 2024-10-08 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_restaurant_id_food_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
    ]
