# Generated by Django 5.1.1 on 2024-10-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_restaurant_food_restaurant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfood',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
