# Generated by Django 5.1.1 on 2024-10-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfood',
            name='quantity',
        ),
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
