# Generated by Django 5.1.1 on 2024-10-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_orderfood_quantity_food_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfood',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
