# Generated by Django 5.1.1 on 2024-10-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_orderfood_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderfood',
            old_name='order_id',
            new_name='order',
        ),
    ]
