# Generated by Django 5.1.1 on 2024-10-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_orderfood_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderfood',
            old_name='food_id',
            new_name='food',
        ),
    ]
