# Generated by Django 5.1.1 on 2024-10-08 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_food_id_orderfood_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='food_items',
        ),
    ]
