# Generated by Django 5.1.1 on 2024-10-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_restaurant_id_food_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_items',
            field=models.ManyToManyField(to='api.food'),
        ),
    ]
