# Generated by Django 5.1.1 on 2024-10-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_order_food_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food_items',
        ),
    ]
