# Generated by Django 5.1.1 on 2024-10-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_order_food_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
