# Generated by Django 5.1.1 on 2024-10-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image_url',
            field=models.ImageField(upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default=None, upload_to='restaurant_logos/'),
        ),
    ]
