# Generated by Django 5.1.1 on 2024-10-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_food_image_url_alter_restaurant_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='image_url',
            new_name='image',
        ),
    ]
