# Generated by Django 5.1.1 on 2024-10-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.CharField(blank=True, default='image', max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
